/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import modelo.Clientes;

/**
 *
 * @author 36127512021.2
 */
public class MenuClientes extends javax.swing.JFrame {

    /**
     * Creates new form MenuClientes
     */
    public MenuClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PesquisarCliente = new javax.swing.JButton();
        EditarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("BEM-VINDO AO MENU DE CLIENTES!!!!");

        PesquisarCliente.setBackground(new java.awt.Color(255, 102, 51));
        PesquisarCliente.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        PesquisarCliente.setText("PESQUISAR");
        PesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarClienteActionPerformed(evt);
            }
        });

        EditarCliente.setBackground(new java.awt.Color(51, 102, 255));
        EditarCliente.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        EditarCliente.setText("EDITAR");
        EditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarClienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setText("AO CLICAR EM PESQUISAR, VOCÊ IRA PESQUISAR OS DADOS DOS CLIENTES CADASTRADOS");

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel3.setText("AO CLICAR EM EDITAR, VOCÊ SERÁ DIRECIONADO PARA A ÁREA DE EDIÇÃO DE CLIENTES");

        voltar.setBackground(new java.awt.Color(255, 153, 102));
        voltar.setFont(new java.awt.Font("Agency FB", 1, 25)); // NOI18N
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(250, 250, 250))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(PesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(EditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(75, 75, 75)
                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarClienteActionPerformed
       String nome = null, cpf = null, endereco = null;
            Clientes model = new Clientes();
            String Consultar = JOptionPane.showInputDialog("Digite o Nome"); 
            
            if (Consultar.equals("")){
               JOptionPane.showMessageDialog(null,"USUÁRIO NÃO ENCONTRADO OU CAMPO EM BRANCO!\n");
               
               dispose();
               MenuClientes MCLIN = new MenuClientes();
               MCLIN.setVisible(true);
         }
          else{  
        try 
	   {           
             String url = "jdbc:mysql://localhost/db_livros";
             String SQL = "SELECT * FROM clientes WHERE nome='"+Consultar+"'";
             
	     Connection conexao = DriverManager.getConnection(url,"root","");
             PreparedStatement pesquisa = conexao.prepareStatement(SQL);	     
             ResultSet resultado = pesquisa.executeQuery();
             
             while (resultado.next()) {  
                nome  = resultado.getString("Nome");
                cpf = resultado.getString("Cpf");
                endereco = resultado.getString("Endereço");
     
           } 
             
	     JOptionPane.showMessageDialog(null,"Dados encontrados com sucesso!\n"+
						                    "------------------------------\n"+
						                    "NOME  : "+nome+"\n"+
						                    "CPF : "+cpf+"\n"+
						                    "ENDEREÇO : "+endereco+"\n"+
						                    "------------------------------"); 
               dispose();
               MenuClientes MCLIN = new MenuClientes();
               MCLIN.setVisible(true);  
	   }
        catch(Exception erro) {            
              JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);                   
        }
            
            }
    }//GEN-LAST:event_PesquisarClienteActionPerformed

    private void EditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarClienteActionPerformed
         String nome = null, cpf = null, endereço = null;
            Clientes model = new Clientes();
            String Consultar = JOptionPane.showInputDialog("Digite o cpf");
            
            if (Consultar.equals("")){
               JOptionPane.showMessageDialog(null,"USUÁRIO NÃO ENCONTRADO OU CAMPO EM BRANCO!\n");
               
         }
          else{
            try 
	   {           
             String url = "jdbc:mysql://localhost/db_livros";
             String SQL = "SELECT * FROM clientes WHERE cpf='"+Consultar+"'";
             
	     Connection conexao = DriverManager.getConnection(url,"root","");
             PreparedStatement pesquisa = conexao.prepareStatement(SQL);	     
             ResultSet resultado = pesquisa.executeQuery();
             
             while (resultado.next()) {  
                nome  = resultado.getString("nome");
                cpf = resultado.getString("cpf");
                endereço = resultado.getString("endereço");
                
           } 
             
	      JOptionPane.showMessageDialog(null,"Dados encontrados com sucesso!\n"+
						                    "------------------------------\n"+
						                    "NOME  : "+nome+"\n"+
						                    "CPF : "+cpf+"\n"+
                                                                    "ENDEREÇO : "+endereço+"\n"+
						                    "------------------------------");
             
            String Editar = JOptionPane.showInputDialog("Qual dado você deseja editar?");
            
            if (Editar.equals("")){
              JOptionPane.showMessageDialog(null,"USUÁRIO NÃO ENCONTRADO OU CAMPO EM BRANCO!\n");
 
           }
            else if (Editar.equals("nome") || (Editar.equals("Nome") || (Editar.equals("NOME")))){
                
                String Nome = JOptionPane.showInputDialog("Digite o novo nome");
         
                String URL02 = "jdbc:mysql://localhost/db_livros";
                String sql = "UPDATE clientes SET nome='"+Nome+"' WHERE cpf='"+Consultar+"'";

                Connection conexao02 = DriverManager.getConnection(url,"root","");
                PreparedStatement atualizar1 = conexao02.prepareStatement(sql);
                atualizar1.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Atualizado com sucesso!");
            }
            else if (Editar.equals("cpf") || (Editar.equals("CPF") || (Editar.equals("Cpf")))){
             
                String CPF = JOptionPane.showInputDialog("Digite o novo cpf");
                
                String URL02 = "jdbc:mysql://localhost/db_livros";
                String sql = "UPDATE clientes SET cpf='"+CPF+"' WHERE cpf='"+Consultar+"'";

                Connection conexao02 = DriverManager.getConnection(url,"root","");
                PreparedStatement atualizar1 = conexao02.prepareStatement(sql);
                atualizar1.executeUpdate();
                JOptionPane.showMessageDialog(null,"Atualizado com sucesso!");
               
            }
            else if (Editar.equals("endereço") || (Editar.equals("Endereço") || (Editar.equals("ENDEREÇO")))){
              
                String Endereço = JOptionPane.showInputDialog("Digite o novo Endereço");
                
                String URL02 = "jdbc:mysql://localhost/db_livros";
                String sql = "UPDATE clientes SET endereço='"+Endereço+"' WHERE cpf='"+Consultar+"'";

                Connection conexao02 = DriverManager.getConnection(url,"root","");
                PreparedStatement atualizar1 = conexao02.prepareStatement(sql);
                atualizar1.executeUpdate();
                JOptionPane.showMessageDialog(null,"Atualizado com sucesso!");  
            }   
	   }
        catch(Exception erro) {            
              JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);                   
        } 
	   }
    }//GEN-LAST:event_EditarClienteActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarCliente;
    private javax.swing.JButton PesquisarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
