/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

/**
 *
 * @author 36127512021.2
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adm = new javax.swing.JButton();
        livro = new javax.swing.JButton();
        clientes = new javax.swing.JButton();
        sair1 = new javax.swing.JButton();

        sair.setBackground(new java.awt.Color(255, 0, 0));
        sair.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        sair.setText("SAIR");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        setSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setText("BEM-VINDO AO BIBLIOTECH!!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 60, 430, 60);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jLabel2.setText("ESCOLHA UMA DAS OPÇÕES!!!");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 140, 440, 50);

        adm.setBackground(new java.awt.Color(255, 102, 51));
        adm.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        adm.setText("ÁREA DO ADM");
        adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admActionPerformed(evt);
            }
        });
        getContentPane().add(adm);
        adm.setBounds(180, 240, 400, 60);

        livro.setBackground(new java.awt.Color(255, 102, 51));
        livro.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        livro.setText("LIVROS");
        livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livroActionPerformed(evt);
            }
        });
        getContentPane().add(livro);
        livro.setBounds(180, 410, 400, 60);

        clientes.setBackground(new java.awt.Color(51, 102, 255));
        clientes.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        clientes.setText("CLIENTES");
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });
        getContentPane().add(clientes);
        clientes.setBounds(180, 320, 400, 60);

        sair1.setBackground(new java.awt.Color(255, 0, 0));
        sair1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        sair1.setText("SAIR");
        sair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair1ActionPerformed(evt);
            }
        });
        getContentPane().add(sair1);
        sair1.setBounds(183, 503, 400, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admActionPerformed
        MenuAdm ADM = new MenuAdm();
        
        ADM.setVisible(true);
    }//GEN-LAST:event_admActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        MenuClientes MCLIN = new MenuClientes();
        
        MCLIN.setVisible(true);
    }//GEN-LAST:event_clientesActionPerformed

    private void livroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livroActionPerformed
        MenuLivro MLI = new MenuLivro();
        
        MLI.setVisible(true);
    }//GEN-LAST:event_livroActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed

    }//GEN-LAST:event_sairActionPerformed

    private void sair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adm;
    private javax.swing.JButton clientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton livro;
    private javax.swing.JButton sair;
    private javax.swing.JButton sair1;
    // End of variables declaration//GEN-END:variables
}
